services:
    api:
        build:
            context: .
            dockerfile: dockerfiles/php/Dockerfile
        image: api
        container_name: api
        ports:
            - "8000:8000"
            - "443:443"
        volumes:
            - .:/var/www/html
        networks:
            - acampsemear
        environment:
            - DB_HOST=db
            - DB_DATABASE=acampsemear
            - DB_USERNAME=root
            - DB_PASSWORD=root
        depends_on:
            - db

    db:
        image: mysql:8.0.37
        container_name: database
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: acampsemear

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - acampsemear
networks:
    acampsemear:
        driver: bridge

volumes:
    db_data:
